apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  index.html: |
    <h1>version 1</h1>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm2
data:
  index.html: |
    <h1>version 2</h1>
